spring.application.name=wasp-backend
spring.datasource.url=jdbc:sqlite:wasp.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
server.port=8080

# Logging level for the MetricRepository class
# Set to DEBUG to see the SQL queries and results, set to INFO to see only the important information
logging.level.com.wasp.wasp_backend.repository.MetricRepository=DEBUG

# Samples per aggregate write for cpu/cpu_cores/memory/disk
# time = window size * send interval
# send interval is currently every 2 seconds
wasp.aggregation.metrics-window-size=10

# Samples per process snapshot write (writes latest process payload).
# separated to keep from overwhelming the database with processwrites
wasp.aggregation.process-window-size=60
